steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/space-launches-repo/space-launches:latest'
      - '-f'
      - 'Containerfile'
      - '.'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/space-launches-repo/space-launches:latest'

timeout: '1800s'
